batch_size: 32
epochs: 3
save_path: saved_models
validation_split: 0.2 # 0-1
models:
  dense_small:
    type: ctn
    loss: mse
    autoencoder_loss: mse
    layers: [32, 32, 32]
  dense_small_large_koopman:
    type: ctn
    layers: [32, 32, 128]
    loss: mse
    autoencoder_loss: mse
  dense_med:
    type: ctn
    layers: [64, 64, 128]
    loss: mse
    autoencoder_loss: mse
  mishmash_small:
    type: mishmash
    loss: mse
    layers: [32, 32, 32]
dataset_folder: "~/koopman_test/datasets"
datasets: 
  - duffing
  - lorentz

hyperparam_combinations:
  - input_window_width: 1
    input_window_skip: 0
    input_window_label_width: 1
  - input_window_width: 6
    input_window_skip: 0
    input_window_label_width: 1
  - input_window_width: 6
    input_window_skip: 0
    input_window_label_width: 4
